In [7]:
!pip install gender_guesser

Requirement already satisfied: gender_guesser in /usr/local/lib/python3.10/dist-packages (0.4.0)

In [8]:
import pandas as pd
import numpy as np
import random
from gender_guesser.detector import Detector

In [11]:
df = pd.read_csv('/content/sample_data/nombres_españoles.csv', sep = ';', header = None)
df = df.rename(columns={0: 'nombre', 1: 'apellido'})

In [13]:
df['edad'] = np.random.randint(65, 100, 50000)
df['discapacidad'] = np.random.randint(0, 2, 50000)
df['pension'] = np.random.randint(10963.40, 42829.29, 50000)
df['familia_numerosa'] = np.random.randint(0, 2, 50000)
df['edad_hijo'] = None
df['trabaja_hijo'] = None

fam_num_index = df[df['familia_numerosa'] == 1].index
for i in (fam_num_index):
    a = len(fam_num_index)
    df['edad_hijo'][i] = np.random.randint(15, 26)

hijo_mayor_index = df[df['edad_hijo'] > 20].index
for i in (hijo_mayor_index):
    a = len(hijo_mayor_index)
    df['trabaja_hijo'][i] = np.random.randint(0, 2)

df['lista_espera'] = np.random.randint(0, 3, 50000)

df['estado_civil'] = None
estados = ['soltero/a', 'casado/a', 'viudo/a']
for i in (df.index):
    df['estado_civil'][i] = random.choice(estados)

df['años_ant'] = np.random.randint(0, 3, 50000)
df['vehiculo'] = np.random.randint(0, 2, 50000)
df['hab_individual'] = np.random.randint(0, 2, 50000)

df['mobilidad'] = None
mobilidad = ['perfecta', 'media', 'limitada']
for i in (df.index):
    df['mobilidad'][i] = random.choice(mobilidad)

df['enfermedad'] = None
enfermedad = ['None', 'terminal']
enfermedad = ['None'] * 99 + ['terminal'] * 1
for i in (df.index):
    df['enfermedad'][i] = random.choice(enfermedad)

df['sexo'] = None
gender_detector = Detector()
df['nombre'] = df['nombre'].astype('str')
df['nombre'] = df['nombre'].apply(lambda x: x.title())
df['apellido'] = df['apellido'].astype('str')
df['apellido'] = df['apellido'].apply(lambda x: x.title())
for i in (df.index):
    df['sexo'][i] = gender_detector.get_gender(df['nombre'][i])

df['trabajo'] = None
trabajos = [
    "Médico",
    "Enfermero/a",
    "Profesor/a",
    "Ingeniero/a",
    "Abogado/a",
    "Arquitecto/a",
    "Administrativo/a",
    "Comercial/Vendedor/a",
    "Electricista",
    "Fontanero/a",
    "Programador/a informático/a",
    "Diseñador/a gráfico/a",
    "Carpintero/a",
    "Fontanero/a",
    "Cocinero/a",
    "Camarero/a",
    "Agricultor/a",
    "Peluquero/a",
    "Fontanero/a",
    "Operario/a de fábrica"
]
for i in (df.index):
    df['trabajo'][i] = random.choice(trabajos)

<ipython-input-13-677c405aa21c>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['edad_hijo'][i] = np.random.randint(15, 26)
<ipython-input-13-677c405aa21c>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trabaja_hijo'][i] = np.random.randint(0, 2)
<ipython-input-13-677c405aa21c>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['estado_civil'][i] = random.choice(estados)
<ipython-input-13-677c405aa21c>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mobilidad'][i] = random.choice(mobilidad)
<ipython-input-13-677c405aa21c>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['enfermedad'][i] = random.choice(enfermedad)
<ipython-input-13-677c405aa21c>:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sexo'][i] = gender_detector.get_gender(df['nombre'][i])
<ipython-input-13-677c405aa21c>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trabajo'][i] = random.choice(trabajos)

In [16]:
df['pension'] = np.random.randint(6784.54, 42829.29, 50000)

,nombre,apellido,edad,discapacidad,pension,familia_numerosa,edad_hijo,trabaja_hijo,lista_espera,estado_civil,años_ant,vehiculo,hab_individual,mobilidad,enfermedad,sexo,trabajo
0,Antonio,Sannicolas,70,1,37597,1,22,1,0,casado/a,1,1,1,media,None,male,Camarero/a
1,Jose,Olloquiegui,99,0,13842,0,None,None,2,casado/a,2,1,1,media,None,male,Fontanero/a
2,Manuel,Vinent,68,1,23492,0,None,None,0,soltero/a,0,0,0,media,None,male,Profesor/a
3,Francisco,Francesch,76,1,37738,1,15,None,2,casado/a,1,1,1,limitada,None,male,Electricista
4,Juan,Calcines,96,0,9287,0,None,None,0,viudo/a,1,1,0,limitada,None,male,Enfermero/a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Tomas,Bu√Ëuel,89,0,9064,0,None,None,2,casado/a,0,1,0,media,None,male,Comercial/Vendedor/a
49996,Agustin,Luchena,86,0,21860,1,17,None,1,soltero/a,0,0,1,perfecta,None,male,Comercial/Vendedor/a
49997,Guillermo,Perdomo,65,1,36849,0,None,None,2,casado/a,2,1,0,perfecta,None,male,Cocinero/a
49998,Gabriel,Baraldes,84,0,28574,0,None,None,0,casado/a,2,0,0,media,None,male,Fontanero/a
49999,Jose Miguel,Goiria,90,1,15732,0,None,None,0,casado/a,0,1,1,limitada,None,unknown,Camarero/a

In [22]:
bins = [6774.54, 12600, 14700, 16800, 18900, 21000, 23100, 25200, 27300, 29400, float('inf')]
etiquetas = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
df['tipo_pension'] = pd.cut(df['pension'], bins=bins, labels=etiquetas)

In [23]:
df

,nombre,apellido,edad,discapacidad,pension,familia_numerosa,edad_hijo,trabaja_hijo,lista_espera,estado_civil,años_ant,vehiculo,hab_individual,mobilidad,enfermedad,sexo,trabajo,tipo_pension
0,Antonio,Sannicolas,70,1,37597,1,22,1,0,casado/a,1,1,1,media,None,male,Camarero/a,J
1,Jose,Olloquiegui,99,0,13842,0,None,None,2,casado/a,2,1,1,media,None,male,Fontanero/a,B
2,Manuel,Vinent,68,1,23492,0,None,None,0,soltero/a,0,0,0,media,None,male,Profesor/a,G
3,Francisco,Francesch,76,1,37738,1,15,None,2,casado/a,1,1,1,limitada,None,male,Electricista,J
4,Juan,Calcines,96,0,9287,0,None,None,0,viudo/a,1,1,0,limitada,None,male,Enfermero/a,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Tomas,Bu√Ëuel,89,0,9064,0,None,None,2,casado/a,0,1,0,media,None,male,Comercial/Vendedor/a,A
49996,Agustin,Luchena,86,0,21860,1,17,None,1,soltero/a,0,0,1,perfecta,None,male,Comercial/Vendedor/a,F
49997,Guillermo,Perdomo,65,1,36849,0,None,None,2,casado/a,2,1,0,perfecta,None,male,Cocinero/a,J
49998,Gabriel,Baraldes,84,0,28574,0,None,None,0,casado/a,2,0,0,media,None,male,Fontanero/a,I
49999,Jose Miguel,Goiria,90,1,15732,0,None,None,0,casado/a,0,1,1,limitada,None,unknown,Camarero/a,C